// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xyvnvmzmochmgqdlqmwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5dm52bXptb2NobWdxZGxxbXdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NjI2MzEsImV4cCI6MjA3MTAzODYzMX0.0g1C0tAuBLHGgfnMaHoxSCOWERYHFHinidWZ7RvBsiU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});